version: '3.8'

services:
  # Marzban VPN Panel
  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: unless-stopped
    env_file: .env
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./xray_config.json:/usr/local/share/xray/xray_config.json:ro
    networks:
      - marzban_net
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: marzban_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: marzban
      MYSQL_USER: marzban
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /var/lib/marzban/mysql:/var/lib/mysql
    command: --bind-address=0.0.0.0 --mysqlx-bind-address=0.0.0.0 --disable-log-bin
    networks:
      - marzban_net

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: marzban_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2053:2053"  # VLESS Reality port
      - "2083:2083"  # Alternative VLESS port
      - "2087:2087"  # Alternative VLESS port
      - "8080:8080"  # Marzban panel port (non-standard)
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - marzban_net
    depends_on:
      - marzban
    command: |
      sh -c 'while :; do
        sleep 6h & wait $${!};
        nginx -s reload;
      done & nginx -g "daemon off;"'

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: marzban_certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: |
      sh -c 'trap exit TERM;
      while :; do
        certbot renew --quiet --no-self-upgrade;
        sleep 12h & wait $${!};
      done;'

networks:
  marzban_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24